czbiohub-sf/coPylot

widgets/hardware/alternative_control.py

- annotation fixes added for two methods and their docstrings shortened

annotation fixes on couple methods of daq code

---

widgets/hardware/alternative_control.py

timelapse control code refactor

---

widgets/gui/qt_live_control.py
widgets/gui/qt_nidaq_worker.py
widgets/gui/qt_timelapse_control.py

Added real calls to NIDaq back and commented out dummy to mimic shutdown delay

Dummy removal

---

widgets/gui/qt_live_control.py
widgets/gui/qt_main_window.py
widgets/gui/qt_timelapse_control.py
widgets/hardware/alternative_control.py

timelapse mode now calls timelapse-specific functions in function passed to worker. Timelapse now also interacts with the status bar.

Making Timelapse Mode Functional

---

widgets/gui/qt_live_control.py
widgets/gui/qt_main_window.py
widgets/gui/qt_timelapse_control.py

- code refactored to have a single threadpool across application

Threadpool refactor

---

.gitignore
copylot/gui/qt_live_control.py
copylot/gui/qt_main_window.py
copylot/gui/qt_parameters_widget.py
copylot/gui/qt_textbox_and_slider.py
copylot/gui/qt_timelapse_control.py
copylot/gui/qt_water_dispenser_widget.py

Ability to save current parameters and selections as default, stored in JSON in a .txt file. Currently built for version without water widget

Save defaults in JSON

---

.pre-commit-config.yaml
README.md

readme update

---

copylot/gui/_qt/job_runners/worker.py
copylot/gui/qt_nidaq_worker.py
copylot/gui/qt_water_dispenser_widget.py

This PR tries to organize certain parts of the codebase to make qthread runners more modular and scalable. Resulting architecture might be subject to changes in future. This PR is not meant to be a final design.

GUI: Organizing qthread runners

---

copylot/gui/_qt/custom_widgets/qt_line_break.py
copylot/gui/qt_live_control.py
copylot/gui/qt_main_window.py
copylot/gui/qt_nidaq_worker.py
copylot/gui/qt_parameters_widget.py
copylot/gui/qt_textbox_and_slider.py
copylot/gui/qt_timelapse_control.py
copylot/gui/qt_water_dispenser_widget.py
requirements.txt

This PR simply migrates direct PyQt5 imports to qtpy for compatibility with both pyqt5 and pyside2.

GUI: migrating imports to qtpy

---

copylot/hardware/hamamatsu_camera/camera.py
copylot/hardware/hamamatsu_camera/dcam.py
copylot/hardware/hamamatsu_camera/dcamapi4.py

This PR adds the dcam api drivers into the codebase and creates the camera class(which will have detailed implementation later).

HW: Adding dcam api

---

copylot/hardware/hamamatsu_camera/camera.py

This PR adds a simple run method to the `Camera` class. This PR is not trying to bring an ultimate modular and capable implementation for such run functionality. Probably, we will update the implementation of this method in a few iterations.

HW: Adding run method to Camera

---

copylot/hardware/asi_stage/stage.py

This PR introduces ASI Stage controller in our hardware submodule. ASI Stage uses its own serial communication standard. Further information about it can be found here: http://asiimaging.com/docs/products/serial_commands .

HW: Adding ASI Stage controller

---

requirements.txt

This PR removes the requirements.txt as it is no longer in use for quite some time and it causes confusion with some IDEs.

requirements.txt removed

---

copylot/hardware/asi_stage/stage.py

This PR addresses a couple fixes on the ASI Stage device class related to serial communication helpers and its enums.

HW: ASI Stage serial communication string encoding fix

---

copylot/hardware/asi_stage/stage.py

This PR introduces breaking changes to improve the asi stage class implementation.

ASI stage class improvements

---

copylot/hardware/asi_stage/demo/stage_demo.py
copylot/hardware/asi_stage/stage.py

This PR adds a small stage demo and fixes issues with stage communication code pieces to run the demo successfully.

HW: ASI stage demo

---

.github/workflows/test_pull_requests.yml

This PR adds the github actions for black and flake8 checks.

Style and format checking Github Action tasks

---

copylot/gui/qt_textbox_and_slider.py
copylot/hardware/ni_daq/control.py

This PR introduced fixes to follow Black style guides.

Black fixes

---

copylot/hardware/asi_stage/demo/axis_info.py
copylot/hardware/asi_stage/stage.py

This PR implements ASI stage info command for fetching specific information on axes of the ASI stage.

HW: ASI stage info command

---

.github/workflows/test_pull_requests.yml
copylot/microscope_config/test/test_microscope_config.py

As we start adding tests we need an automated way to run them for each PR, this PR introduces the required task to run all our test cases.

CI: unit test task

---

docs/source/api/hardware.rst
docs/source/api/introduction.rst
docs/source/index.rst

This PR introduces API reference section on our documentation.

DOC: API reference

---

copylot/gui/_qt/custom_widgets/line_break.py
copylot/gui/_qt/dockables/laser.py
copylot/gui/gui.py

This PR implements a dockable widget to control laser initialized in the system.

GUI: laser dockable widget

---

copylot/hardware/ni_daq/nidaq.py

This PR fixes some typos, changes some names for easier interpretation of the code.

HW: nidaq refactor for readability

---

copylot/gui/_qt/dockables/laser.py

This PR just adds a slider to laser power parameter on GUI as requested in #100 .

GUI: laser power slider

---

copylot/microscope_config/configs/daxi.yaml
copylot/microscope_config/test/test_microscope_config.py

This PR updates daxi microscope config file

updates implemented on config

---

copylot/microscope_config/configs/daxi.yaml
copylot/microscope_config/test/test_microscope_config.py

This PR adds pifoc details to daxi config file.

DaXi config update

---

CONTRIBUTING.md
requirements/development.txt

contributing guidelines updated, notebook added as a depencency

CONTRIBUTING update

---

docs/source/getting_started/hardware_drivers.rst
docs/source/getting_started/install.rst
docs/source/index.rst

This PR adds the getting started section to our documentation. Mainly we will include installation details in this  section for now. There might be  more later in  this section.

DOC: Getting started section

---

copylot/microscope_config/configs/mantis.yaml

This PR adds the mantis.yaml config.

mantis.yaml config

---

requirements/development.txt
setup.cfg

This PR relaxes dependency versions.

Relaxing dependency versions.

---

copylot/hardware/asi_stage/demo/stage_demo.py
copylot/hardware/asi_stage/stage.py

This PR implements independent set speed endpoints for the ASI stage and addresses #115 .

ASI Stage speed for x and y axis independently

---

copylot/microscope_config/configs/dorado.yaml

This PR updates the dorado config yaml file as we started the update the hardware in dorado room.

Dorado config updates

---

copylot/hardware/ni_daq/demo/live_nidaq_demo.py
copylot/hardware/ni_daq/live_nidaq.py

This PR patches the bug introduced in #122 .

BUG: patch for live nidaq demo

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature_request.md

This PR introduces issue templates for the repository.

Issue templates

---

.github/workflows/test_pull_requests.yml
Makefile
copylot/gui/_qt/dockables/live_control.py
copylot/gui/_qt/dockables/water_dispenser.py
copylot/hardware/lasers/vortran/vortran.py
copylot/hardware/mirrors/optotune/demo/demo_mirror.py

This PR addresses the issues raised by PyLint following-up #154 .

Addressing PyLint issues

---

copylot/hardware/lasers/vortran/vortran.py

I noticed a few typos/bugs in the newly merged vortran laser class. I also slightly refactored the `get_lasers` method for clarity. 
There may also be some missing logic at line 419 (where I changed a no-op to `pass`).

Fix bugs and minor refactor in vortran laser class

---

copylot/__init__.py
copylot/gui/_qt/dockables/live_control.py
copylot/gui/_qt/dockables/parameters.py
copylot/gui/gui.py
copylot/hardware/cameras/orca/camera.py
copylot/hardware/filters/arduino_controlled_filterwheel/filterwheel.py
copylot/hardware/lasers/vortran/vortran.py
copylot/hardware/mirrors/optotune/mirror.py
copylot/hardware/pumps/bartels_ux7/bartels_ux7.py
copylot/hardware/stages/asi/stage.py

This PR implements an application-wide logger and migrate print statements to logger calls. Closes #158 .

global logger

---

.github/labeler.yml
.github/workflows/labeler.yml

Pull request labeler action is introduced in this PR.

pr labeler

---

copylot/hardware/cameras/abstract_camera.py

Following issue #166 , this PR adds details that are agreed on to abstract camera class implementation. Tried to achieve a minimalist implementation in abstract class, as we see more opportunities with common functionality in different camera adapters we can revisit abstract class again.

Improved abstract camera

---

copylot/hardware/lasers/vortran/vortran.py

fix typo in valid laser commands
